required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "sigs.k8s.io/kustomize"
  source = "https://github.com/wozniakjan/kustomize"
  branch = "kubernetes-1.13.1"

[prune]
  go-tests = true
  unused-packages = true
