/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	snapshotvalidatorv1alpha1 "github.com/cisco-sso/snapshot-manager/pkg/apis/snapshotvalidator/v1alpha1"
	versioned "github.com/cisco-sso/snapshot-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cisco-sso/snapshot-manager/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cisco-sso/snapshot-manager/pkg/client/listers/snapshotvalidator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ValidationStrategyInformer provides access to a shared informer and lister for
// ValidationStrategies.
type ValidationStrategyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ValidationStrategyLister
}

type validationStrategyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewValidationStrategyInformer constructs a new informer for ValidationStrategy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewValidationStrategyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredValidationStrategyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredValidationStrategyInformer constructs a new informer for ValidationStrategy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredValidationStrategyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnapshotvalidatorV1alpha1().ValidationStrategies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnapshotvalidatorV1alpha1().ValidationStrategies(namespace).Watch(options)
			},
		},
		&snapshotvalidatorv1alpha1.ValidationStrategy{},
		resyncPeriod,
		indexers,
	)
}

func (f *validationStrategyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredValidationStrategyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *validationStrategyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&snapshotvalidatorv1alpha1.ValidationStrategy{}, f.defaultInformer)
}

func (f *validationStrategyInformer) Lister() v1alpha1.ValidationStrategyLister {
	return v1alpha1.NewValidationStrategyLister(f.Informer().GetIndexer())
}
