/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cisco-sso/snapshot-manager/pkg/apis/snapshotmanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeValidationStrategies implements ValidationStrategyInterface
type FakeValidationStrategies struct {
	Fake *FakeSnapshotmanagerV1alpha1
	ns   string
}

var validationstrategiesResource = schema.GroupVersionResource{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Resource: "validationstrategies"}

var validationstrategiesKind = schema.GroupVersionKind{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Kind: "ValidationStrategy"}

// Get takes name of the validationStrategy, and returns the corresponding validationStrategy object, and an error if there is any.
func (c *FakeValidationStrategies) Get(name string, options v1.GetOptions) (result *v1alpha1.ValidationStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(validationstrategiesResource, c.ns, name), &v1alpha1.ValidationStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationStrategy), err
}

// List takes label and field selectors, and returns the list of ValidationStrategies that match those selectors.
func (c *FakeValidationStrategies) List(opts v1.ListOptions) (result *v1alpha1.ValidationStrategyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(validationstrategiesResource, validationstrategiesKind, c.ns, opts), &v1alpha1.ValidationStrategyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ValidationStrategyList{ListMeta: obj.(*v1alpha1.ValidationStrategyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ValidationStrategyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested validationStrategies.
func (c *FakeValidationStrategies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(validationstrategiesResource, c.ns, opts))

}

// Create takes the representation of a validationStrategy and creates it.  Returns the server's representation of the validationStrategy, and an error, if there is any.
func (c *FakeValidationStrategies) Create(validationStrategy *v1alpha1.ValidationStrategy) (result *v1alpha1.ValidationStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(validationstrategiesResource, c.ns, validationStrategy), &v1alpha1.ValidationStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationStrategy), err
}

// Update takes the representation of a validationStrategy and updates it. Returns the server's representation of the validationStrategy, and an error, if there is any.
func (c *FakeValidationStrategies) Update(validationStrategy *v1alpha1.ValidationStrategy) (result *v1alpha1.ValidationStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(validationstrategiesResource, c.ns, validationStrategy), &v1alpha1.ValidationStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationStrategy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeValidationStrategies) UpdateStatus(validationStrategy *v1alpha1.ValidationStrategy) (*v1alpha1.ValidationStrategy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(validationstrategiesResource, "status", c.ns, validationStrategy), &v1alpha1.ValidationStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationStrategy), err
}

// Delete takes name of the validationStrategy and deletes it. Returns an error if one occurs.
func (c *FakeValidationStrategies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(validationstrategiesResource, c.ns, name), &v1alpha1.ValidationStrategy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeValidationStrategies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(validationstrategiesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ValidationStrategyList{})
	return err
}

// Patch applies the patch and returns the patched validationStrategy.
func (c *FakeValidationStrategies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ValidationStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(validationstrategiesResource, c.ns, name, data, subresources...), &v1alpha1.ValidationStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationStrategy), err
}
