/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cisco-sso/snapshot-manager/pkg/apis/snapshotmanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeValidationRuns implements ValidationRunInterface
type FakeValidationRuns struct {
	Fake *FakeSnapshotmanagerV1alpha1
	ns   string
}

var validationrunsResource = schema.GroupVersionResource{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Resource: "validationruns"}

var validationrunsKind = schema.GroupVersionKind{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Kind: "ValidationRun"}

// Get takes name of the validationRun, and returns the corresponding validationRun object, and an error if there is any.
func (c *FakeValidationRuns) Get(name string, options v1.GetOptions) (result *v1alpha1.ValidationRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(validationrunsResource, c.ns, name), &v1alpha1.ValidationRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationRun), err
}

// List takes label and field selectors, and returns the list of ValidationRuns that match those selectors.
func (c *FakeValidationRuns) List(opts v1.ListOptions) (result *v1alpha1.ValidationRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(validationrunsResource, validationrunsKind, c.ns, opts), &v1alpha1.ValidationRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ValidationRunList{ListMeta: obj.(*v1alpha1.ValidationRunList).ListMeta}
	for _, item := range obj.(*v1alpha1.ValidationRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested validationRuns.
func (c *FakeValidationRuns) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(validationrunsResource, c.ns, opts))

}

// Create takes the representation of a validationRun and creates it.  Returns the server's representation of the validationRun, and an error, if there is any.
func (c *FakeValidationRuns) Create(validationRun *v1alpha1.ValidationRun) (result *v1alpha1.ValidationRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(validationrunsResource, c.ns, validationRun), &v1alpha1.ValidationRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationRun), err
}

// Update takes the representation of a validationRun and updates it. Returns the server's representation of the validationRun, and an error, if there is any.
func (c *FakeValidationRuns) Update(validationRun *v1alpha1.ValidationRun) (result *v1alpha1.ValidationRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(validationrunsResource, c.ns, validationRun), &v1alpha1.ValidationRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeValidationRuns) UpdateStatus(validationRun *v1alpha1.ValidationRun) (*v1alpha1.ValidationRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(validationrunsResource, "status", c.ns, validationRun), &v1alpha1.ValidationRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationRun), err
}

// Delete takes name of the validationRun and deletes it. Returns an error if one occurs.
func (c *FakeValidationRuns) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(validationrunsResource, c.ns, name), &v1alpha1.ValidationRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeValidationRuns) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(validationrunsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ValidationRunList{})
	return err
}

// Patch applies the patch and returns the patched validationRun.
func (c *FakeValidationRuns) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ValidationRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(validationrunsResource, c.ns, name, data, subresources...), &v1alpha1.ValidationRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ValidationRun), err
}
