/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cisco-sso/snapshot-manager/pkg/apis/snapshotmanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotReverts implements SnapshotRevertInterface
type FakeSnapshotReverts struct {
	Fake *FakeSnapshotmanagerV1alpha1
	ns   string
}

var snapshotrevertsResource = schema.GroupVersionResource{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Resource: "snapshotreverts"}

var snapshotrevertsKind = schema.GroupVersionKind{Group: "snapshotmanager.ciscosso.io", Version: "v1alpha1", Kind: "SnapshotRevert"}

// Get takes name of the snapshotRevert, and returns the corresponding snapshotRevert object, and an error if there is any.
func (c *FakeSnapshotReverts) Get(name string, options v1.GetOptions) (result *v1alpha1.SnapshotRevert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotrevertsResource, c.ns, name), &v1alpha1.SnapshotRevert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRevert), err
}

// List takes label and field selectors, and returns the list of SnapshotReverts that match those selectors.
func (c *FakeSnapshotReverts) List(opts v1.ListOptions) (result *v1alpha1.SnapshotRevertList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotrevertsResource, snapshotrevertsKind, c.ns, opts), &v1alpha1.SnapshotRevertList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SnapshotRevertList{ListMeta: obj.(*v1alpha1.SnapshotRevertList).ListMeta}
	for _, item := range obj.(*v1alpha1.SnapshotRevertList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotReverts.
func (c *FakeSnapshotReverts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotrevertsResource, c.ns, opts))

}

// Create takes the representation of a snapshotRevert and creates it.  Returns the server's representation of the snapshotRevert, and an error, if there is any.
func (c *FakeSnapshotReverts) Create(snapshotRevert *v1alpha1.SnapshotRevert) (result *v1alpha1.SnapshotRevert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotrevertsResource, c.ns, snapshotRevert), &v1alpha1.SnapshotRevert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRevert), err
}

// Update takes the representation of a snapshotRevert and updates it. Returns the server's representation of the snapshotRevert, and an error, if there is any.
func (c *FakeSnapshotReverts) Update(snapshotRevert *v1alpha1.SnapshotRevert) (result *v1alpha1.SnapshotRevert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotrevertsResource, c.ns, snapshotRevert), &v1alpha1.SnapshotRevert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRevert), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSnapshotReverts) UpdateStatus(snapshotRevert *v1alpha1.SnapshotRevert) (*v1alpha1.SnapshotRevert, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(snapshotrevertsResource, "status", c.ns, snapshotRevert), &v1alpha1.SnapshotRevert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRevert), err
}

// Delete takes name of the snapshotRevert and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotReverts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snapshotrevertsResource, c.ns, name), &v1alpha1.SnapshotRevert{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotReverts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotrevertsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SnapshotRevertList{})
	return err
}

// Patch applies the patch and returns the patched snapshotRevert.
func (c *FakeSnapshotReverts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotRevert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotrevertsResource, c.ns, name, data, subresources...), &v1alpha1.SnapshotRevert{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRevert), err
}
